### ISSUE TITLE
why  index.html is an empty file?

### ISSUE THREAD

**Issue by luckypoem** [leafo/sitegen#2]
hi.
as3:~# git clone https://github.com/leafo/sitegen sitegen-site
as3:~# cd sitegen-site
as3:~/sitegen-site# ls
bin  homepage  README.md  sitegen-dev-1.rockspec  spec
doc  Makefile  sitegen    sitegen.moon
as3:~/sitegen-site# cd homepage
as3:~/sitegen-site/homepage# ls
index.md  README.md  site.moon  snippets  templates  www
as3:~/sitegen-site/homepage# sitegen
Using:  site.moon
rendered        ../doc/plugins.md       ->      www/doc/plugins.html
rendered        README.md       ->      www/README.html
rendered        index.md        ->      www/index.html
feeds:          0
blog posts:     0
as3:~/sitegen-site/homepage# cd www
as3:~/sitegen-site/homepage/www# ls
doc  index.html  README.html  style
as3:~/sitegen-site/homepage/www# nohup Rwebserver 45329 > /dev/null &

visit http://as3.brite.biz:45329/,shows nothing.

as3:~/sitegen-site/homepage/www# ls
doc  index.html  README.html  style
as3:~/sitegen-site/homepage/www# cat index.html
as3:~/sitegen-site/homepage/www#

why  index.html is an empty file?
tks.

**Comment by leafo** [comment]
I'm not sure, but this issue is old so if you're still interested feel free to open again.
