### ISSUE TITLE
Unable to install via luarocks

### ISSUE THREAD

**Issue by lordnynex** [leafo/sitegen#4]
For some reason I see the listing on the moonrocks site but I'm unable to install it via luarocks. Does this need to be republished?

**Comment by leafo** [comment]
What's the message you get?

**Comment by lordnynex** [comment]
No message. `luarocks [search|install] sitegen` returns no results. This *may* be because I installed torch7 which corrupts the base lua install but as far as I can tell from the luarocks config file, it should still point to the main luarocks repo.

**Comment by bdjnk** [comment]
I get the same (no torch7 here). You can download the rockspec and install it manually

**Comment by leafo** [comment]
There's only a dev version of the package uploaded, you need to use the dev manifest

**Comment by rfajfar** [comment]
How to use that dev manifest? Need to replace it somewhere?

**Comment by leafo** [comment]
for future reference, there are directions here for installing from dev manifest: http://luarocks.org/m/root/development-only
